### PR TITLE
Fix twitter uses `name` not `property` attribute

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by jaredkerim** [comment]
@wilsonpage can you rebase this and update the tests? Thanks!

**Comment by jaredkerim** [comment]
Please update the tests and rebase on master.

**Comment by wilsonpage** [comment]
Sorry haven't had chance yet.

**Comment by pdehaan** [comment]
@wilsonpage I can submit a new PR for this against master and update the tests, but I wanted to ask how you felt about leaving the old [invalid] tags in, as well as adding the correct Twitter `<meta>`tags.

Basically feedback on #51.
Should we just try and "do the right thing", even if the user used incorrect meta tags? We'd get better results back in weird edge cases of invalid markup, at the cost of bloating our codebase with extra meta lookups.

**Comment by wilsonpage** [comment]
@pdehaan that's a fair point. TBH the use of `name` instead of `property` is a gotcha, I'm sure others will make the same mistake.

**Comment by pdehaan** [comment]
Per @wilsonpage, yeah, apparently _Reddit_ uses some invalid/un-recommended tags, per https://github.com/mozilla/page-metadata-parser/issues/51#issuecomment-244246180

```html
<meta property="og:description" content="Welcome to r/Funny: reddit&apos;s largest humour depository">
<meta property="og:image" content="https://www.redditstatic.com/icon.png">
<meta property="og:site_name" content="reddit">
<meta property="og:title" content="funny &#x2022; /r/funny">
<meta property="twitter:card" content="summary">
<meta property="twitter:site" content="reddit">
<meta property="twitter:title" content="funny &#x2022; /r/funny">
```

I think we have no choice but to do checks for both `<meta name="">` and `<meta property="">` if we want to get consistent results. Interestingly, running that page through the Twitter Card Validator shows that it's a valid page, so I'm _guessing_ that Twitter looks for `name` and `property` since they know a reasonable %% of people will mess it up.

**Comment by jaredkerim** [comment]
@pdehaan @wilsonpage we must absolutely include both cases in the rules.  The parser doesn't 'care' what the 'intended' structure of markup is, it only cares about *all* the ways to get the relevant data from pages.  That markup is messy and non-conformant is a founding precept of this library.  @pdehaan if you could add both cases to the rules, update the tests, and rebase that would be a huge help!

**Comment by pdehaan** [comment]
> jaredkerim says: _"@pdehaan if you could add both cases to the rules, update the tests, and rebase that would be a huge help!"_

Consider yourself helped, #66!

I totally forgot about #51, but I can do that PR separately, where we basically look for the incorrect format for Open Graph tags as well.

**Pull request closed without merging**
